// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantPOS.Data;

#nullable disable

namespace RestaurantPOS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225183000_AddOrderCustomerName")]
    partial class AddOrderCustomerName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55d918c9-4f86-4cf4-9166-b6d4c9a7c1fb"),
                            Key = "RestaurantName",
                            Value = "Restaurant POS"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.CustomizationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CustomizationItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4a7e147-93a6-47de-9cc9-1706e3f54f90"),
                            IsActive = true,
                            Name = "No Cheese",
                            PriceCents = 0
                        },
                        new
                        {
                            Id = new Guid("6f1f0fd3-1224-4bcf-9f7e-93694dc43071"),
                            IsActive = true,
                            Name = "Extra Cheese",
                            PriceCents = 50
                        },
                        new
                        {
                            Id = new Guid("7b1d6c2a-7d8f-4d6e-8071-71e483f3c4c6"),
                            IsActive = true,
                            Name = "Extra Sauce",
                            PriceCents = 25
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MenuCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b2b9638-b8b9-4b62-8c31-39aefbcb8c50"),
                            IsActive = true,
                            Name = "Burgers",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("5d6f9a8a-dfa0-4a1e-8844-0d9d41a76169"),
                            IsActive = true,
                            Name = "Sides",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("f566ceab-7a9a-4fd3-a7b7-9dd3b9e4f90e"),
                            IsActive = true,
                            Name = "Drinks",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaxRateBps")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd2c0d0a-5297-46a6-9a89-6de819b8f10f"),
                            CategoryId = new Guid("5b2b9638-b8b9-4b62-8c31-39aefbcb8c50"),
                            IsActive = true,
                            Name = "Classic Burger",
                            PriceCents = 799,
                            TaxRateBps = 500
                        },
                        new
                        {
                            Id = new Guid("8b5a657d-c3ef-49d1-b857-09c497ea6341"),
                            CategoryId = new Guid("5b2b9638-b8b9-4b62-8c31-39aefbcb8c50"),
                            IsActive = true,
                            Name = "Cheese Burger",
                            PriceCents = 899,
                            TaxRateBps = 500
                        },
                        new
                        {
                            Id = new Guid("7e3a0d89-0a2e-409d-bb6e-7d72af4de2dc"),
                            CategoryId = new Guid("5b2b9638-b8b9-4b62-8c31-39aefbcb8c50"),
                            IsActive = true,
                            Name = "Veggie Burger",
                            PriceCents = 849,
                            TaxRateBps = 500
                        },
                        new
                        {
                            Id = new Guid("93f3c3e7-7640-4d14-9cd5-3b1f8cbe00b2"),
                            CategoryId = new Guid("5d6f9a8a-dfa0-4a1e-8844-0d9d41a76169"),
                            IsActive = true,
                            Name = "Fries",
                            PriceCents = 299,
                            TaxRateBps = 500
                        },
                        new
                        {
                            Id = new Guid("a7758e44-fef5-41ff-879d-5045e5b84e85"),
                            CategoryId = new Guid("5d6f9a8a-dfa0-4a1e-8844-0d9d41a76169"),
                            IsActive = true,
                            Name = "Onion Rings",
                            PriceCents = 349,
                            TaxRateBps = 500
                        },
                        new
                        {
                            Id = new Guid("f2f09107-0d79-4f51-9df9-c1e5b7af1276"),
                            CategoryId = new Guid("5d6f9a8a-dfa0-4a1e-8844-0d9d41a76169"),
                            IsActive = true,
                            Name = "Garden Salad",
                            PriceCents = 399,
                            TaxRateBps = 500
                        },
                        new
                        {
                            Id = new Guid("ea0de778-6d83-4ea7-b0fd-95b88c4a2f1f"),
                            CategoryId = new Guid("f566ceab-7a9a-4fd3-a7b7-9dd3b9e4f90e"),
                            IsActive = true,
                            Name = "Cola",
                            PriceCents = 199,
                            TaxRateBps = 0
                        },
                        new
                        {
                            Id = new Guid("f439a2a4-0f6e-4f2b-9c5b-7cb1a20d8c7e"),
                            CategoryId = new Guid("f566ceab-7a9a-4fd3-a7b7-9dd3b9e4f90e"),
                            IsActive = true,
                            Name = "Lemonade",
                            PriceCents = 219,
                            TaxRateBps = 0
                        },
                        new
                        {
                            Id = new Guid("1a80d413-98fd-4aac-a785-7e4a84a1ed9c"),
                            CategoryId = new Guid("f566ceab-7a9a-4fd3-a7b7-9dd3b9e4f90e"),
                            IsActive = true,
                            Name = "Iced Tea",
                            PriceCents = 209,
                            TaxRateBps = 0
                        },
                        new
                        {
                            Id = new Guid("9f7d4d8d-1f6d-4c46-9ce0-4b5d7b8f9d1a"),
                            CategoryId = new Guid("f566ceab-7a9a-4fd3-a7b7-9dd3b9e4f90e"),
                            IsActive = true,
                            Name = "Bottled Water",
                            PriceCents = 149,
                            TaxRateBps = 0
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubtotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaxCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineTotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.OrderItemCustomization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomizationItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomizationItemId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("OrderItemCustomizations", (string)null);
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c43e0f9-5f78-4d0d-8b1c-2f623e5bb343"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin",
                            IsActive = true,
                            PinHash = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.MenuCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.OrderItemCustomization", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.CustomizationItem", null)
                        .WithMany()
                        .HasForeignKey("CustomizationItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantPOS.Domain.Entities.OrderItem", null)
                        .WithMany("Customizations")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantPOS.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Payment", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.Order", null)
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
